"""Send AI news summary via Resend email API."""

import os

import requests
from dotenv import load_dotenv

load_dotenv()


def send_email(summary: str, date: str):
    """Send the AI news summary via Resend API."""
    api_key = os.getenv("RESEND_API_KEY")
    recipient = os.getenv("EMAIL_RECIPIENT")

    if not api_key:
        raise ValueError(
            "RESEND_API_KEY not set in .env\n"
            "Get your free API key at https://resend.com"
        )
    if not recipient:
        raise ValueError("EMAIL_RECIPIENT not set in .env")

    html_body = summary.replace("\n", "<br>")
    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.8; color: #333;">
        <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
            {html_body}
            <hr style="border: 1px solid #eee; margin-top: 30px;">
            <p style="font-size: 11px; color: #999;">Generated by AI News Bot</p>
        </div>
    </body>
    </html>
    """

    response = requests.post(
        "https://api.resend.com/emails",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "from": "AI News Bot <onboarding@resend.dev>",
            "to": [recipient],
            "subject": f"🔥 Top 5 AI Trending - {date}",
            "html": html,
            "text": summary,
        },
        timeout=30,
    )
    response.raise_for_status()
    return response.json()
