"""Send AI news summary via email using SMTP."""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from dotenv import load_dotenv

load_dotenv()


def send_email(summary: str, date: str):
    """Send the AI news summary via email.

    Uses Gmail SMTP by default. For other providers, change SMTP_SERVER and SMTP_PORT in .env.
    """
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    recipient = os.getenv("EMAIL_RECIPIENT")
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))

    if not all([sender, password, recipient]):
        raise ValueError(
            "Email not configured. Set these in .env:\n"
            "  EMAIL_SENDER=tu_email@gmail.com\n"
            "  EMAIL_PASSWORD=tu_app_password\n"
            "  EMAIL_RECIPIENT=destino@email.com"
        )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🔥 Top 5 AI Trending - {date}"
    msg["From"] = sender
    msg["To"] = recipient

    # Plain text version
    msg.attach(MIMEText(summary, "plain"))

    # HTML version (nicer formatting)
    html_body = summary.replace("\n", "<br>")
    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6; color: #333;">
        <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
            <h2 style="color: #1a73e8;">🔥 Top 5 AI Trending - {date}</h2>
            <hr style="border: 1px solid #eee;">
            <p>{html_body}</p>
            <hr style="border: 1px solid #eee;">
            <p style="font-size: 12px; color: #888;">Generated by AI News Bot</p>
        </div>
    </body>
    </html>
    """
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())
